### ISSUE TITLE
Memory allocation Error

### ISSUE THREAD

**Issue by priti88** [heuermh/docker-linuxbrew-bio#5]
Hello,
I am trying to run VEP using the docket container. I am getting following Error:

ERROR: Cannot allocate memory at /home/linuxbrew/.linuxbrew/Cellar/vep/81_2015-07-23/lib/Bio/EnsEMBL/Variation/Utils/VEP.pm

I started the docker using 8G limit. 
I was monitoring the memory usage using docker stats while VEP runs, but it never reaches the limit. 
Any idea whats happening?

**Comment by priti88** [comment]
Needed to increase the memory allocation. Works now

**Comment by heuermh** [comment]
Thank you, @priti88
